# Generated by Django 3.2.14 on 2022-11-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(upload_to='static/App/images'),
        ),
    ]
